export const STATS_LOADED = 'ISSUES/STATS_LOADED';
export const STATS_CLEAR = 'ISSUES/STATS_CLEAR';
export const STATS_LOAD_ERROR = 'ISSUES/STATS_LOAD_ERROR';

export const ISSUES_LIST_LOADED = 'ISSUES/LIST_LOADED';
export const ISSUES_LIST_LOAD_ERROR = 'ISSUES/LIST_LOAD_ERROR';
export const ISSUES_LIST_LOADING = 'ISSUES/LIST_LOADING';
export const ISSUES_LIST_CACHE_HIT = 'ISSUES/LIST_CACHE_HIT';
export const ISSUES_LIST_CACHE_RESET = 'ISSUES/LIST_CACHE_RESET';

export const ISSUE_SELECTED = 'ISSUES/SELECTED';
export const ISSUE_LOADING = 'ISSUES/LOADING';
export const ISSUE_CACHE_HIT = 'ISSUES/CACHE_HIT';

export const ISSUE_LOADED = 'ISSUES/LOADED';
export const ISSUE_LOAD_ERROR = 'ISSUES/LOAD_ERROR';

export const ISSUE_UPDATED = 'ISSUES/UPDATED';
export const ISSUE_UPDATE_ERROR = 'ISSUES/UPDATE_ERROR';

export const ISSUE_CREATED = 'ISSUES/CREATED';
export const ISSUE_CREATE_ERROR = 'ISSUES/CREATE_ERROR';

export const ISSUE_DELETED = 'ISSUES/DELETED';
export const ISSUE_DELETE_ERROR = 'ISSUES/DELETE_ERROR';

export const ISSUE_RESTORE_ERROR = 'ISSUES/RESTORE_ERROR';

export const ERROR_GENERAL = 'APP/ERROR_GENERAL';
export const ERROR_HIDE = 'APP/ERROR_HIDE';
